[I 11:12:43.140 NotebookApp] 端口 8888 已经被站用, 请尝试其他端口.
[I 11:12:43.144 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 11:12:43.144 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 11:12:43.144 NotebookApp] http://localhost:8889/?token=d6854900a598eb476e17e35276e7ff20df0ba2dc92dad866
[I 11:12:43.144 NotebookApp]  or http://127.0.0.1:8889/?token=d6854900a598eb476e17e35276e7ff20df0ba2dc92dad866
[I 11:12:43.144 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 11:12:43.149 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-2105-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=d6854900a598eb476e17e35276e7ff20df0ba2dc92dad866
     or http://127.0.0.1:8889/?token=d6854900a598eb476e17e35276e7ff20df0ba2dc92dad866
[I 11:13:11.461 NotebookApp] Creating new notebook in 
[I 11:13:12.518 NotebookApp] Kernel started: 1eaf98bb-4383-4cb2-8af6-54484fceaf35, name: python3
[I 11:14:24.151 NotebookApp] Starting buffering for 1eaf98bb-4383-4cb2-8af6-54484fceaf35:819c0ad7934c4015a0e0f3845495872d
[I 11:14:24.479 NotebookApp] Kernel restarted: 1eaf98bb-4383-4cb2-8af6-54484fceaf35
[I 11:14:24.495 NotebookApp] Restoring connection for 1eaf98bb-4383-4cb2-8af6-54484fceaf35:819c0ad7934c4015a0e0f3845495872d
[I 11:14:24.496 NotebookApp] Replaying 3 buffered messages
[I 11:15:12.514 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[I 11:17:33.785 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 11:17:33.786 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 11:17:33.786 NotebookApp] http://localhost:8888/?token=a9f222d40228c12b307870515ba7533fe9e725e68c8632c9
[I 11:17:33.786 NotebookApp]  or http://127.0.0.1:8888/?token=a9f222d40228c12b307870515ba7533fe9e725e68c8632c9
[I 11:17:33.786 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 11:17:33.793 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-2531-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a9f222d40228c12b307870515ba7533fe9e725e68c8632c9
     or http://127.0.0.1:8888/?token=a9f222d40228c12b307870515ba7533fe9e725e68c8632c9
[I 11:17:38.382 NotebookApp] Kernel started: 94480352-4132-46d7-9fa7-78899cf24ca2, name: python3
[I 11:17:40.292 NotebookApp] Starting buffering for 94480352-4132-46d7-9fa7-78899cf24ca2:d34bbc35a678437c88571d7a6c3d6c76
[I 11:17:40.983 NotebookApp] Starting buffering for 94480352-4132-46d7-9fa7-78899cf24ca2:314be1e73e954a3a8575f227d7e8e7f9
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:19:54.837 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:23:16.195 NotebookApp] Starting buffering for 94480352-4132-46d7-9fa7-78899cf24ca2:e98da5f00bac4d949840fb7348cafd33
[I 11:23:21.339 NotebookApp] Kernel restarted: 94480352-4132-46d7-9fa7-78899cf24ca2
[I 11:23:21.356 NotebookApp] Restoring connection for 94480352-4132-46d7-9fa7-78899cf24ca2:e98da5f00bac4d949840fb7348cafd33
[I 11:23:22.567 NotebookApp] Replaying 6 buffered messages
[I 11:24:10.495 NotebookApp] Saving file at /未命名.ipynb
[I 11:26:11.658 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:28:11.653 NotebookApp] Saving file at /未命名.ipynb
[I 11:30:16.316 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:32:16.315 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:34:16.330 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:36:16.324 NotebookApp] Saving file at /未命名.ipynb
[I 11:38:16.334 NotebookApp] Saving file at /未命名.ipynb
[I 11:40:16.349 NotebookApp] Saving file at /未命名.ipynb
[I 11:42:16.332 NotebookApp] Saving file at /未命名.ipynb
[I 11:44:16.315 NotebookApp] Saving file at /未命名.ipynb
[I 11:44:53.711 NotebookApp] Saving file at /未命名.ipynb
[I 11:50:41.673 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 11:52:41.671 NotebookApp] Saving file at /未命名.ipynb
[I 11:59:41.673 NotebookApp] Saving file at /未命名.ipynb
[I 12:01:41.690 NotebookApp] Saving file at /未命名.ipynb
[I 12:24:26.459 NotebookApp] Saving file at /未命名.ipynb
[I 12:26:26.452 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 12:28:26.467 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 12:30:17.564 NotebookApp] Saving file at /未命名.ipynb
[I 12:30:26.456 NotebookApp] Saving file at /未命名.ipynb
[I 14:34:31.398 NotebookApp] Saving file at /未命名.ipynb
[I 14:56:29.054 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 14:57:38.553 NotebookApp] Saving file at /未命名.ipynb
[I 15:11:11.516 NotebookApp] Saving file at /未命名.ipynb
[I 15:11:53.850 NotebookApp] Starting buffering for 94480352-4132-46d7-9fa7-78899cf24ca2:e98da5f00bac4d949840fb7348cafd33
[I 15:11:54.279 NotebookApp] Kernel restarted: 94480352-4132-46d7-9fa7-78899cf24ca2
[I 15:11:54.294 NotebookApp] Restoring connection for 94480352-4132-46d7-9fa7-78899cf24ca2:e98da5f00bac4d949840fb7348cafd33
[I 15:11:55.813 NotebookApp] Replaying 3 buffered messages
[I 15:13:11.519 NotebookApp] Saving file at /未命名.ipynb
[I 15:17:11.511 NotebookApp] Saving file at /未命名.ipynb
[I 15:19:11.514 NotebookApp] Saving file at /未命名.ipynb
[I 15:21:11.524 NotebookApp] Saving file at /未命名.ipynb
[I 15:23:11.531 NotebookApp] Saving file at /未命名.ipynb
[I 15:25:11.532 NotebookApp] Saving file at /未命名.ipynb
[I 15:27:15.491 NotebookApp] Saving file at /未命名.ipynb
[I 15:31:37.698 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 15:35:43.585 NotebookApp] Saving file at /未命名.ipynb
[I 15:37:43.576 NotebookApp] Saving file at /未命名.ipynb
[I 15:39:43.589 NotebookApp] Saving file at /未命名.ipynb
[I 15:39:50.652 NotebookApp] Saving file at /未命名.ipynb
[I 15:41:43.590 NotebookApp] Saving file at /未命名.ipynb
[I 15:42:53.984 NotebookApp] 302 GET / (::1) 1.190000ms
[I 15:43:43.593 NotebookApp] Saving file at /未命名.ipynb
[I 15:45:40.319 NotebookApp] Shutting down on /api/shutdown request.
[I 15:45:40.325 NotebookApp] 关闭 1 服务
[I 15:45:40.738 NotebookApp] Kernel shutdown: 94480352-4132-46d7-9fa7-78899cf24ca2
[I 15:45:40.741 NotebookApp] Shutting down 0 terminals
[I 15:46:09.444 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:46:09.444 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:46:09.444 NotebookApp] http://localhost:8888/?token=2c0528612405b74d702565864797b0531f17e3031cd98220
[I 15:46:09.444 NotebookApp]  or http://127.0.0.1:8888/?token=2c0528612405b74d702565864797b0531f17e3031cd98220
[I 15:46:09.444 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:46:09.451 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-3487-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=2c0528612405b74d702565864797b0531f17e3031cd98220
     or http://127.0.0.1:8888/?token=2c0528612405b74d702565864797b0531f17e3031cd98220
[I 15:46:14.393 NotebookApp] Shutting down on /api/shutdown request.
[I 15:46:14.394 NotebookApp] 关闭 0 服务
[I 15:46:14.394 NotebookApp] Shutting down 0 terminals
[I 15:46:55.592 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:46:55.592 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:46:55.592 NotebookApp] http://localhost:8888/?token=7cfac859465ce604cd91f67b64f5b726a337fd76192b0acc
[I 15:46:55.592 NotebookApp]  or http://127.0.0.1:8888/?token=7cfac859465ce604cd91f67b64f5b726a337fd76192b0acc
[I 15:46:55.592 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:46:55.598 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-3539-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=7cfac859465ce604cd91f67b64f5b726a337fd76192b0acc
     or http://127.0.0.1:8888/?token=7cfac859465ce604cd91f67b64f5b726a337fd76192b0acc
[I 15:48:24.724 NotebookApp] 302 GET / (::1) 0.630000ms
[W 15:48:25.049 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20201228154655 (::1) 18.250000ms referer=http://localhost:8888/tree?
[I 15:48:26.887 NotebookApp] Shutting down on /api/shutdown request.
[I 15:48:26.891 NotebookApp] 关闭 0 服务
[I 15:48:26.891 NotebookApp] Shutting down 0 terminals
[I 15:48:44.053 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:48:44.055 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:48:44.055 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:48:44.055 NotebookApp] http://localhost:8888/?token=acbb23e1b6d10e070e5f11be4bbb5e4387a0bee72d34be1a
[I 15:48:44.055 NotebookApp]  or http://127.0.0.1:8888/?token=acbb23e1b6d10e070e5f11be4bbb5e4387a0bee72d34be1a
[I 15:48:44.055 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:48:44.065 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-3747-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=acbb23e1b6d10e070e5f11be4bbb5e4387a0bee72d34be1a
     or http://127.0.0.1:8888/?token=acbb23e1b6d10e070e5f11be4bbb5e4387a0bee72d34be1a
[W 15:48:45.948 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228154843 (::1) 13.440000ms referer=http://localhost:8888/tree
[I 15:50:28.163 NotebookApp] Shutting down on /api/shutdown request.
[I 15:50:28.165 NotebookApp] 关闭 0 服务
[I 15:50:28.166 NotebookApp] Shutting down 0 terminals
[I 15:50:36.598 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:50:36.599 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:50:36.599 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:50:36.599 NotebookApp] http://localhost:8888/?token=665903015b0a6904e0c746bb1fb239046c564a9d8d4a0b68
[I 15:50:36.599 NotebookApp]  or http://127.0.0.1:8888/?token=665903015b0a6904e0c746bb1fb239046c564a9d8d4a0b68
[I 15:50:36.599 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:50:36.605 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-3873-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=665903015b0a6904e0c746bb1fb239046c564a9d8d4a0b68
     or http://127.0.0.1:8888/?token=665903015b0a6904e0c746bb1fb239046c564a9d8d4a0b68
[W 15:50:38.396 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155036 (::1) 15.320000ms referer=http://localhost:8888/tree
[I 15:52:19.520 NotebookApp] Shutting down on /api/shutdown request.
[I 15:52:19.523 NotebookApp] 关闭 0 服务
[I 15:52:19.524 NotebookApp] Shutting down 0 terminals
[I 15:52:51.238 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:52:51.239 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:52:51.239 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:52:51.239 NotebookApp] http://localhost:8888/?token=0d062e4d74ec7b2df3983b00053d300f1380aef0ae36eeb4
[I 15:52:51.239 NotebookApp]  or http://127.0.0.1:8888/?token=0d062e4d74ec7b2df3983b00053d300f1380aef0ae36eeb4
[I 15:52:51.239 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:52:51.249 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-3951-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=0d062e4d74ec7b2df3983b00053d300f1380aef0ae36eeb4
     or http://127.0.0.1:8888/?token=0d062e4d74ec7b2df3983b00053d300f1380aef0ae36eeb4
[W 15:52:53.016 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155250 (::1) 15.730000ms referer=http://localhost:8888/tree
[I 15:53:29.233 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:53:29.233 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:53:29.233 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:53:29.233 NotebookApp] http://localhost:8888/?token=06e5cc2da8687d9602c9fbb0a697b62c4e2616b2eb33e141
[I 15:53:29.234 NotebookApp]  or http://127.0.0.1:8888/?token=06e5cc2da8687d9602c9fbb0a697b62c4e2616b2eb33e141
[I 15:53:29.234 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:53:29.238 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-4006-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=06e5cc2da8687d9602c9fbb0a697b62c4e2616b2eb33e141
     or http://127.0.0.1:8888/?token=06e5cc2da8687d9602c9fbb0a697b62c4e2616b2eb33e141
[W 15:53:31.036 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155328 (::1) 15.240000ms referer=http://localhost:8888/tree
[I 15:55:16.988 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:55:16.989 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 15:55:16.989 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 15:55:16.989 NotebookApp] http://localhost:8888/?token=0c9f167b6b138e2c3bd9a6c4a3386e170cbe231f25accc8c
[I 15:55:16.989 NotebookApp]  or http://127.0.0.1:8888/?token=0c9f167b6b138e2c3bd9a6c4a3386e170cbe231f25accc8c
[I 15:55:16.989 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 15:55:16.996 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-4038-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=0c9f167b6b138e2c3bd9a6c4a3386e170cbe231f25accc8c
     or http://127.0.0.1:8888/?token=0c9f167b6b138e2c3bd9a6c4a3386e170cbe231f25accc8c
[W 15:55:18.821 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 25.900000ms referer=http://localhost:8888/tree
[I 15:56:08.087 NotebookApp] 302 GET / (::1) 1.610000ms
[W 15:56:08.525 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 5.940000ms referer=http://localhost:8888/tree?
[W 15:56:09.328 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 3.580000ms referer=http://localhost:8888/tree?
[W 15:56:14.977 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:14.993 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.029 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.036 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.053 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.065 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.082 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.094 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.127 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.134 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.258 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.267 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.348 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.359 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.402 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.411 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.425 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.438 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.457 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.470 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.506 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.513 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.654 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 15:56:15.662 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[I 15:56:16.334 NotebookApp] Kernel started: e1e95e0a-9e4f-4dcf-9095-7ee927132db6, name: python3
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[W 15:57:41.478 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 4.420000ms referer=http://localhost:8888/nbextensions/
[W 15:57:55.894 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 3.320000ms referer=http://localhost:8888/nbextensions/
[W 15:58:00.267 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 3.450000ms referer=http://localhost:8888/nbextensions/
[I 15:58:16.249 NotebookApp] Saving file at /未命名.ipynb
[I 16:00:43.529 NotebookApp] Starting buffering for e1e95e0a-9e4f-4dcf-9095-7ee927132db6:23ec7092720543aa8d72bbad8d222f71
[W 16:01:20.286 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.300 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.334 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.341 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.355 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.372 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.394 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.410 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.456 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.466 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.634 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.643 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.746 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.759 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.806 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.815 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.831 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.845 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.870 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.886 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.924 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:20.933 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:21.096 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:21.108 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:01:24.355 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 7.630000ms referer=http://localhost:8888/tree
[W 16:01:28.885 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228155516 (::1) 8.490000ms referer=http://localhost:8888/tree
[I 16:02:46.383 NotebookApp] Starting buffering for e1e95e0a-9e4f-4dcf-9095-7ee927132db6:cee8b9e162854310b89baa58e6d73ef2
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[I 16:03:55.614 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:03:55.615 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 16:03:55.615 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 16:03:55.615 NotebookApp] http://localhost:8888/?token=db3cfd6045556f1b0ac162f844c1cd2acef392567a584df7
[I 16:03:55.615 NotebookApp]  or http://127.0.0.1:8888/?token=db3cfd6045556f1b0ac162f844c1cd2acef392567a584df7
[I 16:03:55.615 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 16:03:55.624 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-4171-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=db3cfd6045556f1b0ac162f844c1cd2acef392567a584df7
     or http://127.0.0.1:8888/?token=db3cfd6045556f1b0ac162f844c1cd2acef392567a584df7
[W 16:03:57.703 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228160355 (::1) 9.910000ms referer=http://localhost:8888/tree
[W 16:08:51.995 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228160355 (::1) 3.360000ms referer=http://localhost:8888/tree
[I 16:11:24.254 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:11:24.255 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 16:11:24.256 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 16:11:24.256 NotebookApp] http://localhost:8888/?token=8beb465b16d0d7170af35fd1d6300b530e5b1d33b6d4c3e5
[I 16:11:24.256 NotebookApp]  or http://127.0.0.1:8888/?token=8beb465b16d0d7170af35fd1d6300b530e5b1d33b6d4c3e5
[I 16:11:24.256 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 16:11:24.264 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-4743-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=8beb465b16d0d7170af35fd1d6300b530e5b1d33b6d4c3e5
     or http://127.0.0.1:8888/?token=8beb465b16d0d7170af35fd1d6300b530e5b1d33b6d4c3e5
[W 16:11:26.029 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228161123 (::1) 12.800000ms referer=http://localhost:8888/tree
[W 16:11:28.138 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.151 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.185 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.194 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.209 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.221 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.241 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.254 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.291 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.298 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.429 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.437 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.503 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.511 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.543 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.549 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.563 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.576 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.595 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.609 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.644 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.652 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.792 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:11:28.799 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[I 16:11:29.878 NotebookApp] Kernel started: cecd8870-25a9-4026-aadb-82adfd285983, name: python3
[W 16:11:35.177 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228161123 (::1) 9.260000ms referer=http://localhost:8888/nbextensions/
[W 16:11:37.719 NotebookApp] 404 GET /static/components/underscore/underscore-min.map (::1) 2.580000ms referer=None
[W 16:11:39.028 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228161123 (::1) 2.330000ms referer=http://localhost:8888/nbextensions/
[W 16:11:39.287 NotebookApp] 404 GET /static/components/underscore/underscore-min.map (::1) 8.210000ms referer=None
[I 16:19:29.798 NotebookApp] Saving file at /未命名.ipynb
[I 16:19:52.335 NotebookApp] Starting buffering for cecd8870-25a9-4026-aadb-82adfd285983:454d363691994b2884dd2876f760071b
[I 16:19:57.467 NotebookApp] Kernel restarted: cecd8870-25a9-4026-aadb-82adfd285983
[I 16:19:57.498 NotebookApp] Restoring connection for cecd8870-25a9-4026-aadb-82adfd285983:454d363691994b2884dd2876f760071b
[I 16:20:37.790 NotebookApp] Starting buffering for cecd8870-25a9-4026-aadb-82adfd285983:454d363691994b2884dd2876f760071b
[I 16:20:42.951 NotebookApp] Kernel restarted: cecd8870-25a9-4026-aadb-82adfd285983
[I 16:20:42.976 NotebookApp] Restoring connection for cecd8870-25a9-4026-aadb-82adfd285983:454d363691994b2884dd2876f760071b
[I 16:21:29.800 NotebookApp] Saving file at /未命名.ipynb
[I 16:21:36.421 NotebookApp] Saving file at /未命名.ipynb
[I 16:21:38.011 NotebookApp] Starting buffering for cecd8870-25a9-4026-aadb-82adfd285983:454d363691994b2884dd2876f760071b
[W 16:21:38.208 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228161123 (::1) 4.070000ms referer=http://localhost:8888/tree
[W 16:21:40.490 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228161123 (::1) 3.470000ms referer=http://localhost:8888/tree
[I 16:21:42.593 NotebookApp] Shutting down on /api/shutdown request.
[I 16:21:42.595 NotebookApp] 关闭 1 服务
[I 16:21:42.906 NotebookApp] Kernel shutdown: cecd8870-25a9-4026-aadb-82adfd285983
[I 16:21:42.907 NotebookApp] Shutting down 0 terminals
[I 16:22:32.964 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:22:32.964 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 16:22:32.964 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 16:22:32.965 NotebookApp] http://localhost:8888/?token=2965b27430f7018974c37bc7aa4511b6bcbd0a78ce430134
[I 16:22:32.965 NotebookApp]  or http://127.0.0.1:8888/?token=2965b27430f7018974c37bc7aa4511b6bcbd0a78ce430134
[I 16:22:32.965 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 16:22:32.974 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-5098-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=2965b27430f7018974c37bc7aa4511b6bcbd0a78ce430134
     or http://127.0.0.1:8888/?token=2965b27430f7018974c37bc7aa4511b6bcbd0a78ce430134
[W 16:22:34.999 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228162232 (::1) 20.900000ms referer=http://localhost:8888/tree
[I 16:26:17.659 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:26:17.660 NotebookApp] 启动notebooks 在本地路径: /Users/jiaconglin/gitee/crawl-everything
[I 16:26:17.660 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 16:26:17.660 NotebookApp] http://localhost:8888/?token=bb35ef29c1930009896a2508822586573488f4550f519fd8
[I 16:26:17.660 NotebookApp]  or http://127.0.0.1:8888/?token=bb35ef29c1930009896a2508822586573488f4550f519fd8
[I 16:26:17.660 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 16:26:17.667 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jiaconglin/Library/Jupyter/runtime/nbserver-5178-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=bb35ef29c1930009896a2508822586573488f4550f519fd8
     or http://127.0.0.1:8888/?token=bb35ef29c1930009896a2508822586573488f4550f519fd8
[W 16:26:19.372 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228162617 (::1) 12.100000ms referer=http://localhost:8888/tree
[W 16:26:51.357 NotebookApp] 404 GET /static/notebook/js/mathjaxutils.js?v=20201228162617 (::1) 3.350000ms referer=http://localhost:8888/tree
[W 16:26:58.231 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.247 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.285 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.293 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.312 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.325 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.345 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.358 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.398 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.407 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.709 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.723 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.831 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.841 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.871 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.878 NotebookApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.889 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.900 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.915 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.926 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.958 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:58.982 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:59.158 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:26:59.165 NotebookApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[I 16:26:59.869 NotebookApp] Kernel started: 51694414-0166-4961-a573-b21675b7618f, name: python3
[I 16:40:08.260 NotebookApp] Saving file at /未命名.ipynb
[I 16:45:16.989 NotebookApp] Saving file at /未命名.ipynb
[I 16:47:22.059 NotebookApp] Saving file at /未命名.ipynb
[I 16:49:22.066 NotebookApp] Saving file at /未命名.ipynb
[I 16:49:42.626 NotebookApp] Saving file at /未命名.ipynb
[I 16:51:11.986 NotebookApp] Saving file at /未命名.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/jiaconglin/gitee/crawl-everything/crawl/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 16:53:22.055 NotebookApp] Saving file at /未命名.ipynb
[I 17:46:19.225 NotebookApp] Starting buffering for 51694414-0166-4961-a573-b21675b7618f:88165e276f894cfeace89987bb8397c1
